In [1]:
import tensorflow as tf

In [32]:
def cube(x):
    return x**3

cube(2)

8

In [36]:
# calling functions with tensorflow
cube(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [37]:
# Python function to Tensorflow function
tf_cube = tf.function(cube)
tf_cube

In [38]:
tf_cube(2)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [39]:
tf_cube(tf.constant(2.))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [40]:
# create Tensorflow function using decorator

@tf.function
def tf_cube(x):
    return x**3

tf_cube(2)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [42]:
# original function
tf_cube.python_function(2)

8