In [1]:
import tensorflow as tf

In [2]:
t = tf.constant([
    [1,2,3],
    [10,20,30],
    [-1,0,1]
])
t

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [10, 20, 30],
       [-1,  0,  1]])>

In [4]:
type(t)

tensorflow.python.framework.ops.EagerTensor

In [5]:
t.shape

TensorShape([3, 3])

In [6]:
t.dtype

tf.int32

In [7]:
t[:, 1:]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  3],
       [20, 30],
       [ 0,  1]])>

In [8]:
t[..., tf.newaxis]

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3]],

       [[10],
        [20],
        [30]],

       [[-1],
        [ 0],
        [ 1]]])>

In [9]:
t+10

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [20, 30, 40],
       [ 9, 10, 11]])>

In [11]:
tf.square(t)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  1,   4,   9],
       [100, 400, 900],
       [  1,   0,   1]])>

In [12]:
t @ tf.transpose(t)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  14,  140,    2],
       [ 140, 1400,   20],
       [   2,   20,    2]])>

In [13]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

### Tensorflow and NumPy

In [14]:
import numpy as np

In [15]:
a = np.array([1,2,3])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [17]:
# tensorflow to numpy
t.numpy()

array([[ 1,  2,  3],
       [10, 20, 30],
       [-1,  0,  1]])

In [19]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [20]:
np.square(t)

array([[  1,   4,   9],
       [100, 400, 900],
       [  1,   0,   1]])

### Type Conversions

In [22]:
# ERROR: cannot add float and int in tensorflow
tf.constant(2.) + tf.constant(32)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 

In [26]:
# ERROR: cannot add 32-bit with 64-bit
tf.constant(2.) + tf.constant(32., dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 

In [29]:
t2 = tf.constant(32., dtype=tf.float64)
tf.constant(2.0,) + tf.cast(t2, dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=34.0>

### Variables

In [40]:
v = tf.Variable([1])
v

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([1])>

In [41]:
v + 5

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([6])>

In [43]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([2])>